In [1]:
import torch
# torch.empty(size): uninitiallized
x = torch.empty(1)
x = torch.empty(3)
x = torch.empty(2,3)
x = torch.rand(2,2,3)

x=torch.rand(5,3)
x=torch.zeros(5,3)

print(x.size())
print(x.shape)
x.size(0)
x.shape[0]

print(x.dtype)
x=torch.zeros(5,3,dtype=torch.float16)
print(x)
print(x.dtype)
x=torch.tensor([5.5,3])
print(x.dtype)
x = torch.tensor([5.5, 3], requires_grad=True)
print(x)
x.dtype

torch.Size([5, 3])
torch.Size([5, 3])
torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.float16
torch.float32
tensor([5.5000, 3.0000], requires_grad=True)


torch.float32

In [42]:
x=torch.tensor([5.5,3], requires_grad=True)
x
x = torch.ones(2,2)
y = torch.rand(2,2)
z=x+y
print(x,y,z)

z=x-y
z=torch.sub(x,y)

x=x*y
z=torch.mul(x,y)

z=x/y
z=torch.div(x,y)

x=torch.rand(5,3)
x
print(x[:,0])
print(x[1,:])
print(x[1,1])
# Get the actual value if only 1 element in your tensor
x[1,1].item()

x=torch.rand(4,4)
y=x.view(16)
z=x.view(-1,8)
print(x.size(),y.size(),z.size())

a=torch.ones(5)
b=a.numpy()
b
print(type(b))

a.add_(1)
a
b

import numpy as np
a = np.ones(5)
b=torch.from_numpy(a)
c=torch.tensor(a)
a
b
c
a+=1
a
b
c
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x = torch.rand(2,2).to(device)  # move tensors to GPU device
#x = x.to("cpu")
#x = x.to("cuda")  

x = torch.rand(2,2, device=device)  # or directy create them on GPU

tensor([[1., 1.],
        [1., 1.]]) tensor([[0.9183, 0.5698],
        [0.2607, 0.8099]]) tensor([[1.9183, 1.5698],
        [1.2607, 1.8099]])
tensor([0.7776, 0.0446, 0.7832, 0.1181, 0.6040])
tensor([0.0446, 0.4903, 0.5658])
tensor(0.4903)
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
<class 'numpy.ndarray'>


In [47]:
x=torch.ones(2,2)
y=torch.rand(2,2)
z=x+y
x
y
z
z=x-y
z=torch.sub(x,y)
z=x*y
z=torch.mul(x,y)
z=x/y
z=torch.div(x,y)
# Slicing
x = torch.rand(5,3)
print(x)
print("x[:, 0]", x[:, 0]) # all rows, column 0
print("x[1, :]", x[1, :]) # row 1, all columns
print("x[1, 1]", x[1,1]) # element at 1, 1

# Get the actual value if only 1 element in your tensor
print("x[1,1].item()", x[1,1].item())
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())