In [1]:
import torch
# torch.empty(size): uninitiallized
x = torch.empty(1)
x = torch.empty(3)
x = torch.empty(2,3)
x = torch.rand(2,2,3)

x=torch.rand(5,3)
x=torch.zeros(5,3)

print(x.size())
print(x.shape)
x.size(0)
x.shape[0]

print(x.dtype)
x=torch.zeros(5,3,dtype=torch.float16)
print(x)
print(x.dtype)
x=torch.tensor([5.5,3])
print(x.dtype)
x = torch.tensor([5.5, 3], requires_grad=True)
print(x)
x.dtype

torch.Size([5, 3])
torch.Size([5, 3])
torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.float16
torch.float32
tensor([5.5000, 3.0000], requires_grad=True)


torch.float32

In [42]:
x=torch.tensor([5.5,3], requires_grad=True)
x
x = torch.ones(2,2)
y = torch.rand(2,2)
z=x+y
print(x,y,z)

z=x-y
z=torch.sub(x,y)

x=x*y
z=torch.mul(x,y)

z=x/y
z=torch.div(x,y)

x=torch.rand(5,3)
x
print(x[:,0])
print(x[1,:])
print(x[1,1])
# Get the actual value if only 1 element in your tensor
x[1,1].item()

x=torch.rand(4,4)
y=x.view(16)
z=x.view(-1,8)
print(x.size(),y.size(),z.size())

a=torch.ones(5)
b=a.numpy()
b
print(type(b))

a.add_(1)
a
b

import numpy as np
a = np.ones(5)
b=torch.from_numpy(a)
c=torch.tensor(a)
a
b
c
a+=1
a
b
c
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x = torch.rand(2,2).to(device)  # move tensors to GPU device
#x = x.to("cpu")
#x = x.to("cuda")  

x = torch.rand(2,2, device=device)  # or directy create them on GPU

tensor([[1., 1.],
        [1., 1.]]) tensor([[0.9183, 0.5698],
        [0.2607, 0.8099]]) tensor([[1.9183, 1.5698],
        [1.2607, 1.8099]])
tensor([0.7776, 0.0446, 0.7832, 0.1181, 0.6040])
tensor([0.0446, 0.4903, 0.5658])
tensor(0.4903)
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
<class 'numpy.ndarray'>


In [47]:
x=torch.ones(2,2)
y=torch.rand(2,2)
z=x+y
x
y
z
z=x-y
z=torch.sub(x,y)
z=x*y
z=torch.mul(x,y)
z=x/y
z=torch.div(x,y)
# Slicing
x = torch.rand(5,3)
print(x)
print("x[:, 0]", x[:, 0]) # all rows, column 0
print("x[1, :]", x[1, :]) # row 1, all columns
print("x[1, 1]", x[1,1]) # element at 1, 1

# Get the actual value if only 1 element in your tensor
print("x[1,1].item()", x[1,1].item())
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())
a = torch.ones(5)
print(a)

# torch to numpy with .numpy()
b = a.numpy()
print(b)
print(type(b))
# Careful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other
a.add_(1)
print(a)
print(b)# numpy to torch with .from_numpy(x), or torch.tensor() to copy it
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
c = torch.tensor(a)
print(a)
print(b)
print(c)

# again be careful when modifying
a += 1
print(a)
print(b)
print(c)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x = torch.rand(2,2).to(device)  # move tensors to GPU device
#x = x.to("cpu")
#x = x.to("cuda")  

x = torch.rand(2,2, device=device)  # or directy create them on GPU

In [58]:
import torch
x=torch.randn(3, requires_grad=True)
y=x+2
x
y
y.grad_fn

z=y*y*3
z
z=z.mean()
z
x.grad
z.backward()
x.grad



In [73]:
a=torch.randn(2,2)
b=(a*a).sum()
a.requires_grad
b.grad_fn

a.requires_grad_(True)
b = (a*a).sum()
a.requires_grad
b.grad_fn

a=torch.randn(2,2,requires_grad=True)
b=a.detach()
a.requires_grad
b.requires_grad

a=torch.rand(2,2,requires_grad=True)
a.requires_grad
with torch.no_grad():
    b=a**2
    print(b.requires_grad)
 

False


In [80]:
import torch

# Linear regression
# f = w * x  + b
# here : f = 2 * x

X = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8], dtype=torch.float32)
Y = torch.tensor([2, 4, 6, 8, 10, 12, 14, 16], dtype=torch.float32)

w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)

# model output
def forward(x):
    return w * x

# loss = MSE
def loss(y, y_pred):
    return ((y_pred - y)**2).mean()

X_test = 5.0

print(f'Prediction before training: f({X_test}) = {forward(X_test).item():.3f}')

Prediction before training: f(5.0) = 0.000


In [81]:
# training
learning_rate = 0.01
n_epochs=100

for epoch in range(n_epochs):
    # predict = forward pass
    y_pred = forward(X)
    # loss
    l = loss(Y, y_pred)
    # calculate gradient = backward pass
    l.backward()

    # update weights
    # w.data = w.data-learning_rate*w.grad
    with torch.no_grad():
        w -= learning_rate * w.grad
    # zero the gradient after updating
    w.grad.zero_()
    if (epoch+1) %10 == 0:
        print(f'epoch{epoch+1}:w={w.item():.3f}, loss={l.item():.3f}')

print(f'prediction after train: f({X_test}) = {forward(X_test).item():.3f}')

epoch10:w=1.998, loss=0.000
epoch20:w=2.000, loss=0.000
epoch30:w=2.000, loss=0.000
epoch40:w=2.000, loss=0.000
epoch50:w=2.000, loss=0.000
epoch60:w=2.000, loss=0.000
epoch70:w=2.000, loss=0.000
epoch80:w=2.000, loss=0.000
epoch90:w=2.000, loss=0.000
epoch100:w=2.000, loss=0.000
prediction after train: f(5.0) = 10.000


In [ ]:
import torch
import torch.nn as nn